version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile-web
        ports:
            - "80:9000"
        depends_on:
            - db
        environment:
            - POSTGRES_PASSWORD=mypassword
            - POSTGRES_USER=postgres
    db:
        build:
            context: .
            dockerfile: Dockerfile-db
        environment:
            - POSTGRES_PASSWORD=mypassword
            - POSTGRES_USER=postgres